MVCMenus/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCMenus.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVCMenus/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCMenus.Entities;

namespace MVCMenus.Controllers
{
    [Authorize]
    public class MenusController : Controller
    {
        // GET: Menus
        public ActionResult Index()
        {
            List<Menus> m;
            using (var r = new MenusEntities())
            {
                m = r.Menus.ToList();
            }
            return View(m);
        }

        [HttpGet]
        [ActionName("Create")]
        public ActionResult Create_Get()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Create")]
        public ActionResult Create_Post()
        {
            var menusmodel = new Menus();
            TryUpdateModel(menusmodel);

            using (var r = new MenusEntities())
            {
                r.Menus.Add(menusmodel);
                r.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Details(string code)
        {
            var menumodel = new Menus();
            TryUpdateModel(menumodel);

            using (var r = new MenusEntities())
            {
                menumodel = r.Menus.FirstOrDefault(x => x.MenuCode == code);
            }

            return View(menumodel);
        }

        [HttpGet]
        [ActionName("Edit")]
        public ActionResult Edit_Get(string code)
        {
            var menumodel = new Menus();
            TryUpdateModel(menumodel);

            using (var r = new MenusEntities())
            {
                menumodel = r.Menus.Where(x => x.MenuCode == code).FirstOrDefault();
            }

            return View(menumodel);
        }

        [HttpPost]
        [ActionName("Edit")]
        public ActionResult Edit_Post(string code)
        {
            var menumodel = new Menus();
            TryUpdateModel(menumodel);

            using (var r = new MenusEntities())
            {
                var m = r.Menus.Where(x => x.MenuCode == code).FirstOrDefault();
                TryUpdateModel(m);
                r.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        [ActionName("Delete")]
        public ActionResult Delete_Get(string code)
        {
            var menumodel = new Menus();
            TryUpdateModel(menumodel);

            using (var r = new MenusEntities())
            {
                menumodel = r.Menus.FirstOrDefault(x => x.MenuCode == code);
            }

            return View(menumodel);
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult Delete_Post(string code)
        {
            var menumodel = new Menus();
            TryUpdateModel(menumodel);

            using (var r = new MenusEntities())
            {
                var m = r.Menus.Remove(r.Menus.FirstOrDefault(x => x.MenuCode == code));
                TryUpdateModel(m);
                r.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

MVCMenus/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVCMenus/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title</h2>
<h3>Rich Brony Catering</h3>

<address>
    Indonesian food specialist catering<br />
    Poji, WA 088382818888<br />
</address>

<address>
    <strong>Marketing:</strong>   <a href="mailto:Support@example.com">cuco@gmail.com</a>
</address>

MVCMenus/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div style="margin:auto; width: 100%; padding: 100px">
    <h1 style="text-align:center">Rich Brony Catering</h1>
    <hr />
    <div class="row" style="text-align:center; margin: auto">
        <h4 class="col-md-6">@Html.ActionLink("Create Menu", "Create", "Menus")</h4>
        <h4 class="col-md-6 links">@Html.ActionLink("List Menu", "Index", "Menus")</h4>
    </div>